name: Jenkins to GitHub Actions

on: 
  push:

jobs:
  install-dependencies-1818055014:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: 'Install Dependencies: Run shell command'
      run: |
        npm install  # This will install all dependencies, including Vite

  build-1075488164:
    needs: install-dependencies-1818055014
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: 'Build: Run shell command'
      run: |
        npm run build  # This should work now as Vite is installed

  test--2089507673:
    needs: build-1075488164
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: 'Test: Run shell command'
      run: npm test
